app:
  title: Backstage Uffizzi Environment
  baseUrl: ${UFFIZZI_URL}

backend:
  baseUrl: ${UFFIZZI_URL}
  cors:
    origin: ${UFFIZZI_URL}
    methods: [GET, POST, PUT, DELETE]
    credentials: true
