app:
  title: Backstage Uffizzi Environment
  baseUrl: ${UFFIZZI_URL}

backend:
  baseUrl: ${UFFIZZI_URL}
  cors: null
    # origin: ${UFFIZZI_URL}
    # methods: [GET, POST, PUT, DELETE]
    # credentials: true
